### ISSUE TITLE
Missing token rewards

### ISSUE THREAD

**Issue by bperham** [WeatherXM/issue-tracker#101]
## WeatherXM Related Element

- Web Dashboard

## **Describe the bug**
I don't see token rewards for July 1, 4, or 5.

### **How To Reproduce**
1. Go to Web Console
2. View Earnings Bar Graph
3. There is no bar for July 1, 4 or 5.

### **Expected behavior**
Expected to see a bar for those days.

### **If Applicable: Desktop (please complete the following information):**
 - OS: All
 - Browser: All

Stations: Bent Denim Avalanche and Overt Hickory Breeze

**Comment by PavlosTze** [comment]
The issue has been identified and we are working to fix it. Thank you for reporting it that @bperham :)

**Comment by PavlosTze** [comment]
Issue has been fixed. :)

**Comment by bperham** [comment]
I see it fixed for July 1 but July 4 and 5 are still missing.

![image](https://user-images.githubusercontent.com/34038083/177610433-5c5c4c32-688b-4ab4-9600-f850e9c518ee.png)

**Comment by bperham** [comment]
Side note suggestion: it would be nice to see the date under the bar for each day.

**Comment by PavlosTze** [comment]
@bperham Can you please check if there have been 3 transactions today on blockchain on your address?

We conducted today 3 transactions, one for July 4th, one for July 5th and one for today (July 6th). So if there are the transactions on blockchain, but not visible in the console (like on your screenshot above) that is a UI issue, but we have a new web app under development which will soon be launched and get rid of that console.

So we will get rid of all those issues.

But if these 3 transactions aren't there on the blockchain then that's a more important bug that we need to look further into. Please check and let me know!

**Comment by bperham** [comment]
Yes, I see 6 transactions from 9 hours ago. Probably 3 for each of my 2
stations.
