### ISSUE TITLE
Web Explorer sometimes doesn't show hexes

### ISSUE THREAD

**Issue by RevNotDev** [WeatherXM/issue-tracker#11]
## WeatherXM Related Element
Please pick one of the following WeatherXM elements that are applicable for this bug:
- Website

## **Describe the bug**
The web Explorer finishes loading but no station hexes show up. The whole map is blank.

### **How To Reproduce**
(This doesn't happen every time, it seems to be intermittent. )
1. Go to https://explorer.weatherxm.com/
2. No station hexes load 
3. Only a refresh of the page will show the hexes

### **Expected behavior**
The hexes should show when the webpage has loaded

### **If Applicable: Desktop (please complete the following information):**
 - OS: W11
 - Browser: Chrome
 - Version: 98.0.4758.102

### **Screenshot**
![image](https://user-images.githubusercontent.com/46647866/155799243-ae21cee3-2a6a-4595-aea8-0c6972e80bb4.png)

**Comment by lynadi** [comment]
Fixed

**Comment by RevNotDev** [comment]
Still the same for me. Just loaded up the explorer, no hexes showed, refreshed the page and they showed up.

**Comment by EmperorDRT1** [comment]
I'm able to reproduce the issue. When I first visit the explorer, no hexes are shown. The hexes return when I refresh the page. 

OS: W11
Browser: Chrome
Version: 97.0.4692.99
