### ISSUE TITLE
[BUG] Refresh of weather station page leaves Rewards section in inconsistent state 

### ISSUE THREAD

**Issue by Greg15** [WeatherXM/issue-tracker#50]
## WeatherXM Related Element
- Android Application

## **Describe the bug**
If the Rewards display mode (24H, 7D or 30D) is set to either 7D or 30D, the selected Rewards button is inconsistent with the Rewards display mode after the weather station details page is refreshed. The 7D or 30D button remains selected after refresh, but the Rewards display mode reverts to 24H.

### **How To Reproduce**
1. From home page of app, click on a weather station to launch the weather station details page
2. Scroll down to Rewards section. Notice that by default '24H' is selected.
3. Click on either '7D' or '30D'
4. Notice the Rewards amount change to the 7D or 30D rewards, and a graph is shown
5. Scroll back to top of details page, and do a page refresh by doing a "swipe down" motion
6. Scroll back down to Rewards section
7. Notice the Rewards amount and display (with no graph) has changed to the 24H graph, but the 7D or 30D button is still selected.
8. Notice that you cannot click on the already selected 7D or 30D button to see the desired 7D or 30D total and graph. To get back to the desired 7D or 30D info, click on the 24H button, then click back on the 7D or 30D button.

### **Expected behavior**
Upon page refresh, either the selected Rewards button should revert to 24H to match the reverted Rewards display mode, or the Rewards display mode should remain in the pre-refresh mode (e.g. 7D total and graph) to match the button.
I suspect the 2nd approach is most consistent with other refresh behavior on that page, such as when 'Tomorrow' weather data is selected before doing a page refresh, but either approach is probably fine.

### **Screenshots**
![Screenshot_20220420-125519.png](https://user-images.githubusercontent.com/70354350/164300321-08644a6a-28b7-4077-be83-9e9c4023253d.png)

### **Smartphone**
 - Device: moto g7 power
 - OS: android version 10
 - Android App Version 3.0.8-49c9f79

**Comment by PavlosTze** [comment]
Fixed in the latest version that was released today. Thank you for your help! :)

**Comment by Greg15** [comment]
@PavlosTze This big still exists in app version 3.0.9-511ce1b.

You might need to reopen it.

**Comment by PavlosTze** [comment]
Closed by accident. Fixed internally, but the fix will be included in the next release.

Therefore I am reopening it and will get back to it on the next release.

**Comment by Greg15** [comment]
I've noticed a related issue. The internal fix likely solves it as well, but wanted to bring it to your attention.

I start on the same app page, and the 7D or 30D rewards view is selected. I switch to a different app, and say away from the WeatherXM app long enough so that when I later switch back, the app itself will initiate a refresh.
Then I switch back to the weatherXM app. For a brief moment, the display is correct, but the app-initiated page refresh then leaves the rewards display in the same inconsistent state.

My assumption is your internal fix probably fixes any refresh, so I'm not concerned. But thought I'd bring it up.

**Comment by PavlosTze** [comment]
@Greg15 The fix should fix also this issue. But when this is released it would be great if you could confirm this also :)

**Comment by Greg15** [comment]
I've noticed a related issue. Let me know if I should open a separate bug or if the internal fix already solves it.
From the app homepage, click on a station, and then QUICKLY AND IMMEDIATELY scroll down to the rewards section and click on 30D or 7D BEFORE the hourly weather data is retrieved and populated (winning this race condition sometimes is easy, sometimes it is not - might need to close app, clear cache, wait long enough for the app to believe it must regather hourly upcoming weather data, etc).
When the hourly weather data populates, the daily reward amount is also rendered in the rewards box, but the 30D or 7D button remains selected.

**Comment by PavlosTze** [comment]
No need to open a new issue @Greg15 , I will handle this in the current fix :)

Thank you!

**Comment by PavlosTze** [comment]
Thanks for reporting that @Greg15 . This just got fixed in the latest beta release therefore I am closing this issue.

**Comment by Greg15** [comment]
@PavlosTze The race condition is not solved. If I immediately click 30D upon page load, when the page finishes initializing, it shows today's token rewards but 30D selected
![Screenshot_20220512-122042.png](https://user-images.githubusercontent.com/70354350/168133777-f6e425da-b16b-4300-a0e1-159e6ba3744c.png)

**Comment by Greg15** [comment]
@PavlosTze the other variation seems to be unresolved as well, in which I put the rewards display in 30D mode, then navigate to other apps for sufficient time and usage so that when I toggle back to the WeatherXM app, it causes the app to refresh the page automatically. In that case, the refresh displays the 24H earnings, but leaves the 30D label selected
![Screenshot_20220513-133434.png](https://user-images.githubusercontent.com/70354350/168346606-f77d02e2-33ce-4464-bdcd-d0a397e61cd5.png)

**Comment by PavlosTze** [comment]
> @PavlosTze although the basic page refresh portion is solved, the race condition is not solved. If I immediately click 30D upon page load, when the page finishes initializing, it shows today's token rewards but 30D selected.
> 
> I confirmed on version 3.1.0-3a64cd1
> 
> (I have not yet confirmed resolution of the other bug variation)
> 
> ![Screenshot_20220512-122042.png](https://user-images.githubusercontent.com/70354350/168133777-f6e425da-b16b-4300-a0e1-159e6ba3744c.png)

This is fixed internally, will probably be out in the next beta release :)
